# Generated by Django 4.0.4 on 2022-05-16 10:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import works_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('works_core', '0002_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=works_core.models.default_urls, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works_core.city', verbose_name='Город')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works_core.specialization', verbose_name='Язык программирования')),
            ],
            options={
                'unique_together': {('city', 'specialization')},
            },
        ),
    ]
