# Generated by Django 4.0.4 on 2022-05-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_core', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-time_stamp'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
