# Generated by Django 4.0.4 on 2022-05-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
